const $ = (s) => document.querySelector(s); let identities=[];
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function api(url, options){const r=await fetch(url,options);const data=await r.json();if(!r.ok)throw new Error(data.error||'Request failed');return data}
function date(v){return v?new Date(v).toLocaleString(): '—'}
async function loadOverview(){const d=await api('/api/overview');$('#stats').textContent=`${d.notes} notes · ${d.conversations} turns · ${d.identities} identities · ${d.embeddingModel}`}
async function loadIdentities(){const d=await api('/api/identities');identities=d.identities;for(const id of ['user-identity','assistant-identity']){$('#'+id).innerHTML='<option value="">Select identity…</option>'+identities.map(x=>`<option value="${esc(x.id)}">${esc(x.name)}${x.description?' — '+esc(x.description):''}</option>`).join('')}$('#identity-detail').innerHTML=identities.length?`<p class="eyebrow">AVAILABLE IDENTITIES</p>${identities.map(x=>`<div class="result"><span class="meta">${x.hasVoiceSample?'VOICE SAMPLE AVAILABLE':'TEXT IDENTITY'} · created ${date(x.createdAt)}</span><h3>${esc(x.name)}</h3><p>${esc(x.description||'No description')}</p>${x.sampleUrl?`<audio controls src="${esc(x.sampleUrl)}"></audio>`:''}</div>`).join('')}`:''}
function card(r){return `<article class="result" data-id="${esc(r.id)}"><span class="meta">${esc((r.labels||[]).slice(0,2).join(' · ')||r.author||'archived item')} <b class="score">${Number(r.score).toFixed(3)}</b></span><h3>${esc(r.summary)}</h3><p class="meta">${date(r.createdAt)} · ${esc(r.author||'unknown')}</p></article>`}
async function search(kind){const isNotes=kind==='notes', query=$(isNotes?'#notes-query':'#conversation-query').value;const data=await api('/api/search',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({collection:isNotes?'notes':'conversation_transcripts',query,count:Number($(isNotes?'#notes-count':'#conversation-count').value),recencyBias:Number($(isNotes?'#notes-recency':'#conversation-recency').value),transcriptLabel:isNotes?undefined:$('#conversation-label').value})});const target=$(isNotes?'#notes-results':'#conversation-results');target.classList.remove('empty');target.innerHTML=data.results.length?data.results.map(card).join(''):'No semantic matches.';target.querySelectorAll('.result').forEach(e=>e.onclick=()=>preview(e.dataset.id))}
async function preview(id){const {item}=await api('/api/items/'+encodeURIComponent(id));let media='';const source='/api/items/'+encodeURIComponent(id)+'/preview';if(item.hasPreview){if(item.kind==='image')media=`<img src="${source}">`;else if(item.kind==='audio')media=`<audio controls src="${source}"></audio>`;else if(item.kind==='video')media=`<video controls src="${source}"></video>`;else media=`<a href="${source}" target="_blank">Open archived file</a>`}$('#preview-content').innerHTML=`<p class="eyebrow">${esc(item.collection)} / ${esc(item.kind)}</p><h2>${esc(item.originalName||item.author||'Stored item')}</h2><p class="meta">Created ${date(item.createdAt)}<br>Edited ${date(item.updatedAt)}<br>Embedded with ${esc(item.embeddingModel)}<br>${esc((item.labels||[]).join(' · '))}</p><p>${esc(item.summary)}</p>${media}<pre>${esc(item.text||JSON.stringify(item.transcript,null,2))}</pre>`;$('#preview').classList.add('open')}
document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{document.querySelectorAll('.tab,.view').forEach(x=>x.classList.remove('active'));t.classList.add('active');$('#'+t.dataset.view).classList.add('active')});document.querySelectorAll('[data-search]').forEach(b=>b.onclick=()=>search(b.dataset.search).catch(e=>alert(e.message)));$('#close-preview').onclick=()=>$('#preview').classList.remove('open');
$('#new-identity').onclick=()=>$('#identity-dialog').showModal();$('#save-identity').onclick=async e=>{e.preventDefault();try{await api('/api/identities',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:$('#identity-name').value,description:$('#identity-description').value})});$('#identity-dialog').close();$('#identity-name').value='';$('#identity-description').value='';await loadIdentities();await loadOverview()}catch(err){alert(err.message)}};
function importData(){const file=$('#import-file').files[0];if(!file)throw new Error('Choose an export JSON file.');if(!$('#user-identity').value||!$('#assistant-identity').value)throw new Error('Select both identities first.');const fd=new FormData();fd.append('file',file);fd.append('userIdentityId',$('#user-identity').value);fd.append('assistantIdentityId',$('#assistant-identity').value);return fd}
$('#import-form').onsubmit=async e=>{e.preventDefault();try{$('#import-status').textContent='Reading final messages…';const r=await api('/api/import/openrouter/preview',{method:'POST',body:importData()});const user=identities.find(x=>x.id===$('#user-identity').value)?.name||'User',assistant=identities.find(x=>x.id===$('#assistant-identity').value)?.name||'Assistant';$('#import-review').innerHTML=`<p class="eyebrow">${r.turns.length} FINAL MESSAGES · REASONING EXCLUDED</p><h2>Check the order.</h2><div class="results">${r.turns.map(t=>`<article class="result"><span class="meta">${t.role==='user'?esc(user):esc(assistant)} · ${date(t.createdAt)}${t.isEdited?' · edited':''}</span><h3>${esc(t.text)}</h3></article>`).join('')}</div>`;$('#embed-import').hidden=false;$('#import-status').textContent='Review the labeled turns, then embed.'}catch(err){$('#import-status').textContent=err.message}};
$('#embed-import').onclick=async()=>{try{$('#import-status').textContent='Embedding final messages…';const r=await api('/api/import/openrouter',{method:'POST',body:importData()});$('#import-status').textContent=`Embedded ${r.embedded} final messages. Reasoning skipped.`;$('#embed-import').hidden=true;await loadOverview()}catch(err){$('#import-status').textContent=err.message}};
const algoSpecs=[['memory-initial','Memory candidates',false],['notes-initial','Notes / media candidates',true],['notes-sentence','Note sentence filter',false],['conversations-initial','Conversation candidates',true],['conversations-sentence','Conversation sentence filter',false]];
function algoCard([key,title,recency]){const isSentence=key.includes('sentence'),isContentCandidate=key==='notes-initial'||key==='conversations-initial',mode=key==='memory-initial'?'auto':'top-k',topK=isSentence?4:isContentCandidate?3:5;return `<section class="algo-card"><h4>${title}</h4><label>Selection algorithm<select id="${key}-mode"><option value="top-k"${mode==='top-k'?' selected':''}>Top K</option><option value="threshold">Threshold</option><option value="range">Threshold + range</option><option value="auto"${mode==='auto'?' selected':''}>Auto threshold</option></select></label><div class="algo-fields"><label>Top K<input id="${key}-top-k" type="number" value="${topK}" min="1"></label><label>Threshold<input id="${key}-threshold" type="number" value=".55" min="0" max="2" step=".01"></label><label>Minimum<input id="${key}-min" type="number" value="2" min="1"></label><label>Maximum<input id="${key}-max" type="number" value="8" min="1"></label>${recency?`<label>Recency bias<input id="${key}-recency" type="number" value="${key.startsWith('conversations')?.5:0}" min="0" max="2" step=".1"></label>`:''}</div></section>`}
$('#algo-panels').innerHTML=algoSpecs.map(algoCard).join('');
function selection(key){return {mode:$(`#${key}-mode`).value,topK:Number($(`#${key}-top-k`).value),threshold:Number($(`#${key}-threshold`).value),minCandidates:Number($(`#${key}-min`).value),maxCandidates:Number($(`#${key}-max`).value)}}
function parseMultipliers(raw){return Object.fromEntries(String(raw||'').split(/[\n,]+/).map(x=>x.trim()).filter(Boolean).map(x=>x.split('=').map(y=>y.trim())).filter(x=>x[0]&&Number.isFinite(Number(x[1]))).map(([k,v])=>[k,Number(v)]))}
let hintAgents=[];
async function loadHintAgents(){const data=await api('/api/hints/agents');hintAgents=data.agents;$('#hint-agent').innerHTML=hintAgents.map(a=>`<option value="${esc(a.name)}">${esc(a.name)}</option>`).join('');const preferred=hintAgents.find(a=>a.name.toLowerCase()==='telos-code')||hintAgents[0];if(preferred){$('#hint-agent').value=preferred.name;applyAgentDefaults(preferred)}}
function applyAgentDefaults(agent){const m=agent.memory||{},cats=agent.effectiveCategories||m.categories||[];$('#hint-categories').value=cats.map(x=>x.name).join(', ');$('#hint-category-multipliers').value=cats.filter(x=>Number.isFinite(x.multiplier)).map(x=>`${x.name}=${x.multiplier}`).join('\n');$('#hint-uncategorized').checked=m.includeUncategorized!==false;$('#hint-fallback').value=m.fallbackCategory||'';$('#hint-depth').value=m.searchMaxDepth||3;$('#hint-beam').value=m.searchBeamWidth||8;$('#hint-chains').value=m.searchMaxChains||8;$('#hint-overall').value=m.overallEmbeddingWeight??.35;$('#hint-aggregation').value=m.searchDefaultAggregationMode||'max';$('#hint-weighting').value=m.autoHints?.userPhraseWeighting||'embedding';$('#hint-enabled').checked=m.autoHints?.enabled!==false;$('#hint-tool-enabled').checked=m.autoHints?.toolResponses?.enabled!==false;$('#hint-max-length').value=m.autoHints?.toolResponses?.maxQueryLength||4000;}
$('#hint-agent').addEventListener('change',()=>applyAgentDefaults(hintAgents.find(a=>a.name===$('#hint-agent').value)||{}));$('#hint-kind').addEventListener('change',()=>{const a=hintAgents.find(x=>x.name===$('#hint-agent').value)||{},tool=$('#hint-kind').value==='tool-response';$('#hint-weighting').value=tool?(a.memory?.autoHints?.toolResponsePhraseWeighting||'embedding'):(a.memory?.autoHints?.userPhraseWeighting||'embedding')});
document.querySelectorAll('.source-mix input[type=range]').forEach(input=>input.addEventListener('input',()=>input.nextElementSibling.value=Number(input.value).toFixed(2)));
function hintPayload(){const kind=$('#hint-kind').value;return {query:$('#hint-query').value,agentName:$('#hint-agent').value,categories:$('#hint-categories').value.split(',').map(x=>x.trim()).filter(Boolean),categoryMultipliers:parseMultipliers($('#hint-category-multipliers').value),options:{queryKind:kind,maxQueryLength:Number($('#hint-max-length').value),queryPhraseWeightingMode:$('#hint-weighting').value,memory:{weight:Number($('#weight-memory').value),maxDepth:Number($('#hint-depth').value),beamWidth:Number($('#hint-beam').value),maxChains:Number($('#hint-chains').value),overallEmbeddingWeight:Number($('#hint-overall').value),phraseAggregationMode:$('#hint-aggregation').value,includeUncategorized:$('#hint-uncategorized').checked,fallbackCategory:$('#hint-fallback').value||undefined,candidateSelection:selection('memory-initial')},notes:{weight:Number($('#weight-notes').value),recencyBias:Number($('#notes-initial-recency').value),candidateSelection:selection('notes-initial'),sentenceSelection:selection('notes-sentence')},conversations:{weight:Number($('#weight-conversations').value),recencyBias:Number($('#conversations-initial-recency').value),candidateSelection:selection('conversations-initial'),sentenceSelection:selection('conversations-sentence')}}}}
function renderHints(data){const phrases=data.queryPhrases||[];$('#hint-phrases').classList.toggle('empty',!phrases.length);$('#hint-phrases').innerHTML=phrases.length?phrases.map(p=>`<span class="phrase-pill"><b>${esc(p.text)}</b><small>${esc(p.type)} · ${Number(p.weight).toFixed(3)}</small><i style="width:${Math.min(100,Number(p.weight)*100)}%"></i></span>`).join(''):'No weighted phrases extracted.';const metrics={memory:data.memory,notes:data.notes,conversations:data.conversations};$('#hint-sections').classList.toggle('empty',!data.sections?.length);$('#hint-sections').innerHTML=(data.sections||[]).map((s,i)=>`<article class="hint-card" data-source="${esc(s.source)}"><h4>${esc(s.source)} hint ${i+1}</h4><p class="trace">weighted score ${Number(s.weightedScore).toFixed(4)} · source ${metrics[s.source]?.durationMs??'?'} ms · total ${data.durationMs} ms</p><pre>${esc(s.text)}</pre></article>`).join('')||'No hint candidates survived selection.';$('#hint-text').textContent=data.text||'';$('#hint-status').textContent=`${phrases.length} weighted phrases · ${data.sections?.length||0} hint blocks · ${data.durationMs} ms`;}
$('#run-hints').onclick=async()=>{if(!$('#hint-enabled').checked)return $('#hint-status').textContent='Auto hints are disabled for this test.';if($('#hint-kind').value==='tool-response'&&!$('#hint-tool-enabled').checked)return $('#hint-status').textContent='toolResponses hints are disabled for this test.';$('#hint-status').textContent='Analyzing phrases and searching all sources…';$('#run-hints').disabled=true;try{const data=await api('/api/hints/test',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(hintPayload())});renderHints(data)}catch(e){$('#hint-status').textContent=e.message}finally{$('#run-hints').disabled=false}};
Promise.all([loadOverview(),loadIdentities(),loadHintAgents()]).catch(e=>console.error(e));
