name: AcademicAgent
planner:
  provider: gemini
  model: models/gemini-flash-latest
  system_prompt_file: planner_system.txt
  temperature: 1
executor:
  provider: gemini
  model: models/gemini-flash-latest
  system_prompt_file: executor_system.txt
  temperature: 1
tools:
  - calendar
  - search
  - presentation