// OS tool - AI-based system control tools
import { exec } from 'child_process';
import { promisify } from 'util';
import chalk from 'chalk';

const execAsync = promisify(exec);

/**
 * Execute custom Python script generated by AI
 * @param {string} prompt - Detailed description of the script/application to create
 * @returns {Promise<string>} Script execution result
 */
async function customScript(prompt) {
  try {
    if (!prompt) {
      throw new Error('Требуется параметр prompt');
    }

    console.log(chalk.blue(`\n🐍 Запуск AI-скриптера для создания скрипта: "${prompt}"`));
    
    // Escape quotes for Windows command line
    const escapedPrompt = prompt.replace(/"/g, '""');
    const command = `G:\\agent0\\realtime\\.venv\\Scripts\\python.exe G:\\telos\\ComputerUse\\ai_scripter.py --prompt "${escapedPrompt}"`;
    
    console.log(chalk.gray(`📝 Выполняется команда: ${command}`));
    
    const { stdout, stderr } = await execAsync(command, {
      maxBuffer: 10 * 1024 * 1024, // 10MB buffer
      encoding: 'utf8',
      env: {
        ...process.env,
        PYTHONIOENCODING: 'utf-8'
      }
    });

    if (stderr && stderr.trim()) {
      console.log(chalk.yellow(`⚠️ Предупреждения: ${stderr}`));
    }

    const result = stdout.trim() || 'Скрипт выполнен успешно (нет вывода)';
    console.log(chalk.green('✅ Скрипт выполнен успешно'));
    
    return result;
  } catch (error) {
    console.error(chalk.red('❌ Ошибка выполнения customScript:'), error.message);
    return `Ошибка выполнения скрипта: ${error.message}`;
  }
}

/**
 * Execute computer control task using AI agent
 * @param {string} task - Detailed description of the task to perform (in English)
 * @returns {Promise<string>} Task execution result
 */
async function computerUse(task) {
  try {
    if (!task) {
      throw new Error('Требуется параметр task');
    }

    console.log(chalk.blue(`\n💻 Запуск AI-агента для управления компьютером: "${task}"`));
    
    // Escape quotes for Windows command line
    const escapedTask = task.replace(/"/g, '""');
    const command = `G:\\agent0\\realtime\\.venv\\Scripts\\python.exe G:\\telos\\ComputerUse\\computer_controller.py --task "${escapedTask}"`;
    
    console.log(chalk.gray(`📝 Выполняется команда: ${command}`));
    
    const { stdout, stderr } = await execAsync(command, {
      maxBuffer: 10 * 1024 * 1024, // 10MB buffer
      encoding: 'utf8',
      env: {
        ...process.env,
        PYTHONIOENCODING: 'utf-8'
      }
    });

    if (stderr && stderr.trim()) {
      console.log(chalk.yellow(`⚠️ Предупреждения: ${stderr}`));
    }

    const result = stdout.trim() || 'Задача выполнена успешно (нет вывода)';
    console.log(chalk.green('✅ Задача выполнена успешно'));
    
    return result;
  } catch (error) {
    console.error(chalk.red('❌ Ошибка выполнения computerUse:'), error.message);
    return `Ошибка выполнения задачи: ${error.message}`;
  }
}

// Export tool in system format
export const os = {
  /**
   * Execute custom AI-generated Python script
   * Runs any custom Python script generated by AI based on prompt description
   * @param {string} prompt - Detailed description of the script/application to create
   * @returns {Promise<string>} Script execution result
   */
  customScript: async (prompt) => {
    try {
      console.log(chalk.blue('\n🤖 Выполняется операция: os.customScript'));
      return await customScript(prompt);
    } catch (error) {
      console.error(chalk.red('❌ Ошибка в os.customScript:'), error.message);
      return `Ошибка: ${error.message}`;
    }
  },

  /**
   * Execute computer control task using AI agent
   * Specialized agent that uses the computer like a human - can perform all actions a human can
   * @param {string} task - Detailed description of the task to perform (in English)
   * @returns {Promise<string>} Task execution result
   */
  computerUse: async (task) => {
    try {
      console.log(chalk.blue('\n🤖 Выполняется операция: os.computerUse'));
      return await computerUse(task);
    } catch (error) {
      console.error(chalk.red('❌ Ошибка в os.computerUse:'), error.message);
      return `Ошибка: ${error.message}`;
    }
  }
};

